# Text Deduplication Configuration

# Data Settings
data:
  input_file: "data/raw/sample_call_center.csv"
  output_file: "data/processed/deduplicated.csv"
  text_column: "texts"
  label_column: "labels"

# Model Settings
model:
  name: "BAAI/bge-base-en-v1.5"  # Efficient and accurate model for semantic similarity
  batch_size: 32
  device: "auto"  # Will use GPU if available

# Deduplication Settings
deduplication:
  initial_threshold: 0.8  # Similarity threshold (will be converted to distance)
  min_threshold: 0.7
  max_threshold: 0.9
  adaptive_threshold: true
  min_text_length: 3
  max_text_length: 1000
  
# Clustering Settings
clustering:
  method: "dbscan"  # Using DBSCAN for better semantic clustering
  min_cluster_size: 2  # Minimum number of similar texts to form a cluster
  
# Visualization Settings
visualization:
  similarity_heatmap_max_samples: 100
  cluster_viz_max_samples: 1000
  interactive_mode: true
  
# Logging Settings
logging:
  level: "INFO"
  file: "dedup_log.txt"
  console: true 